version: '3.1'

services:

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    # E2E TEST DB: NO AUTHENTICATION NEEDED
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    # COMMAND TO LINK MONGO SERVICE TO CONTAINER: >> docker exec -it mongodb mongosh
    # IF NOT CONFIGURED IN TERMINAL DB IS NOT REACHABLE
