name: API CI

# proyectos que no sean monorepos
# on: [push]

# para monorepos
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yaml"

default:
  run:
    working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install Dependency
        shell: bash
        run: npm ci # Instalacion de dependencias para Countinous Integration
      - name: Run Unit Test
        shell: bash
        run: npm run test

